### ISSUE TITLE
Strange KDE-related error exposing malware-like behavior

### ISSUE THREAD

**Issue by LupeChristoph** [Nitrokey/nitrokey-app2#54] opened 2023-04-26 13:45 UTC
```
lupe@XXXX:/sw/archive/Nitrokey$ ./nitrokey-app-v2.0.1-x64-linux-binary
kde-open5: /tmp/_MEIvnI6L7/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libKF5KIOCore.so.5)
kde-open5: /tmp/_MEIvnI6L7/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libKF5CoreAddons.so.5)
kde-open5: /tmp/_MEIvnI6L7/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libKF5Service.so.5)
kde-open5: /tmp/_MEIvnI6L7/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libKF5ConfigWidgets.so.5)
kde-open5: /tmp/_MEIvnI6L7/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libKF5WindowSystem.so.5)
kde-open5: /tmp/_MEIvnI6L7/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libKF5ConfigCore.so.5)
kde-open5: /tmp/_MEIvnI6L7/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libQt5Xml.so.5)
```
The strange thing is that the error is triggered by a version of libstdc++.so in a somewhat randomly named subdirectory of /tmp. This something that point to malware behavior. Please explain. BTW, please note that the files I'm attaching are from a later run of the Nitrokey App, so the name of the subdirectory differs.

The message above are triggered by clicking the (?) symbol in the App's window. OS is Ubuntu 22.10 (Kinetic Kudu) with up to date patches.

I'm attaching the nitrokey-app2.log and an strace of the run producing the error messages. Since this made me aware that I had forgotten to secure /tmp, I did that. Which prevents the error from occurring:
```
lupe@alanya:/sw/archive/Nitrokey$ ./nitrokey-app-v2.0.1-x64-linux-binary
./nitrokey-app-v2.0.1-x64-linux-binary: error while loading shared libraries: libz.so.1: failed to map segment from shared object
```
I'm attaching an strace log for this as well.

Let me repeat that putting executable code in /tmp or /var/tmp and running it from there is a deplorable practice. Please rewrite your code to avoid this.

I have not yet analyzed the straces, so I do not yet know how your code wants to work. I'm glad it pointed me at the lack of security on my /tmp and /var/tmp. Thank you for that!

**Comment by szszszsz** [comment] 2023-04-26 15:57
Hey! Let me add just for the record, I saw this one on Fedora 36 as well

**Comment by daringer** [comment] 2023-04-27 10:47
Hey, yeah generally this is expected behavior for the single-file-binary in Linux environments.
nitrokey-app2 is actually a python application and to provide a single executable we are using https://pyinstaller.org/en/stable/operating-mode.html#bundling-to-one-file (where you read more about the details). Generally without doing assumptions about the directory structure using `/tmp` is the most obvious way to do so.

Nevertheless it is better to have installation done through your package manager or `pip`, but we haven't published it yet to pypi, we will do so soon. 

In general, did the app start for you with the initial error? Because with "securing" `/tmp` you mean likely that you forbid execution inside `/tmp` right, so afterwards it won't start for sure, right?

**Comment by robin-nitrokey** [comment] 2023-04-27 10:47
The extraction to `/tmp` is done by PyInstaller, the tool used to generate the single executable: https://pyinstaller.org/en/stable/operating-mode.html#how-the-one-file-program-works

If you want to avoid this, you can manually run nitrokey-app2 as described here:
https://github.com/Nitrokey/nitrokey-app2#compiling-for-linux-and-macos

**Comment by szszszsz** [comment] 2023-04-27 11:36
Do you consider this solved? What about the original error?

**Comment by LupeChristoph** [comment] 2023-04-27 11:51
> In general, did the app start for you with the initial error? Because with "securing" /tmp you mean likely that you forbid execution inside /tmp right, so afterwards it won't start for sure, right?

> Do you consider this solved? What about the original error?

No, I don't. Let me expand a bit:

When I give it the expected permissions on /tmp (on /tmp type ext4 (rw,noatime)), the app looks like this:
![nitrokey-app](https://user-images.githubusercontent.com/1870827/234852710-e4f19814-168e-4f11-9cce-9ee97a332341.png)

The leftmost button on the lower left side works OK. The second button gives me the errors I described initially. The remaining two do not work. The button on the upper left side, below the red image, also works. As does the update feature as far as I can tell - the Nitrokey is already up to date.

**Comment by LupeChristoph** [comment] 2023-04-27 11:52
> The extraction to /tmp is done by PyInstaller, the tool used to generate the single executable: https://pyinstaller.org/en/stable/operating-mode.html#how-the-one-file-program-works

> If you want to avoid this, you can manually run nitrokey-app2 as described here:
https://github.com/Nitrokey/nitrokey-app2#compiling-for-linux-and-macos

Thanks for the precise explanation. That is very useful to know.

**Comment by daringer** [comment] 2024-02-15 15:58
please use the flathub package: https://flathub.org/apps/com.nitrokey.nitrokey-app2 (currently no nk3mini update is possible there currently, will be fixed with one of the next releases)

**Closed by daringer** 2024-02-15 15:58 UTC
Labels: os

**Comment by LupeChristoph** [comment] 2024-02-15 16:10
> please use the flathub package: https://flathub.org/apps/com.nitrokey.nitrokey-app2

Easier said than done. Ubuntu is already riddled with Snap. I will not add another such mess. No, I've never looked at Flathub. I'm pretty content with deb packages and I'm considering converting to Debian or some other distribution that does not require Snap, Flat, or anything else like that.

So in essence you are saying that this problem will not be fixed, right? Just great! Is the manual method I linked above still supported?

**Comment by daringer** [comment] 2024-02-15 22:03
The single-binary for Linux is simply not compatible enough for a wider range of distributions - it will likely be dropped in one of the next releases - flathub is the way to go and something I would consider something that is "free" (snap is not in my eyes) - we are also working on improving "packagability" for pynitrokey and nitrokey-app2 then deb-packages will also be available ... installing through pip(x) is currently not tested in depth, but this will also stay as a way to install "manually"
