### ISSUE TITLE
Transparent text on kde/gentoo

### ISSUE THREAD

**Issue by runcom** [Nitrokey/nitrokey-app2#58] opened 2023-04-28 06:53 UTC
Not sure why it is, but launching the app from the main branch gives me what's in the screenshot.

![Screenshot_20230428_085104](https://user-images.githubusercontent.com/849915/235075685-06f92b51-ec30-4729-886a-acf784cb1817.png)

**Comment by PureTryOut** [comment] 2023-05-02 11:27
Distro in use isn't relevant here, the used theme is. This seems to only happen on dark themes, in OP's and my case Breeze Dark from KDE Plasma.

**Comment by bordenc** [comment] 2023-05-09 22:42
Is it replicated in other dark themes (Gnome, XFCE, etc?)

**Comment by bordenc** [comment] 2023-05-10 00:54
This is a bit of a no-brainer. The issue is all usage of `color` and `background-color` in the `*.ui` files in `nitrokeyapp/ui` folder.

One way to deal with this is to make sure that both background-color and color are always defined together, since defining a white background and Qt providing the white text causes problems.

A better way is to use [Qt's PaletteRole](https://doc.qt.io/qt-5/stylesheet-reference.html#paletterole) properties, since users generally define themes with good reason and overriding them can cause accessibility issues (for example, overriding a high-contrast theme)

**Comment by robin-nitrokey** [comment] 2023-06-27 18:55
Should be fixed by https://github.com/Nitrokey/nitrokey-app2/pull/92, will probably be released this week.

**Closed** 2023-07-26 16:25 UTC
