### ISSUE TITLE
show update button only for Nitrokeys requiring an update

### ISSUE THREAD

**Issue by Niklap97** [Nitrokey/nitrokey-app2#136] opened 2023-07-26 16:08 UTC
- hide/disable Update-Button when Nitrokey has latest firmware

**Comment by robin-nitrokey** [comment] 2023-07-26 17:46
duplicate of: https://github.com/Nitrokey/nitrokey-app2/issues/84

**Comment by daringer** [comment] 2023-07-28 22:06
closing in favor #84

**Closed by daringer** 2023-07-28 22:06 UTC
Labels: ui
